# Generated by Django 5.0.4 on 2026-04-24 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("location", models.CharField(blank=True, max_length=100)),
                ("subject", models.CharField(blank=True, max_length=100)),
                ("total_expected", models.IntegerField(default=0)),
                ("total_detected", models.IntegerField(default=0)),
                ("total_recognized", models.IntegerField(default=0)),
                (
                    "classroom_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="classroom_photos/%Y/%m/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="class_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-start_time"],
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("check_in_time", models.TimeField(blank=True, null=True)),
                ("check_out_time", models.TimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Present"),
                            ("ABSENT", "Absent"),
                            ("LATE", "Late"),
                            ("HALF_DAY", "Half Day"),
                        ],
                        default="PRESENT",
                        max_length=20,
                    ),
                ),
                (
                    "attendance_mode",
                    models.CharField(
                        choices=[
                            ("KIOSK", "Kiosk (Individual)"),
                            ("CLASSROOM", "Classroom (Bulk)"),
                            ("MANUAL", "Manual Override"),
                        ],
                        default="KIOSK",
                        max_length=20,
                    ),
                ),
                ("confidence_score", models.FloatField(default=0.0)),
                ("location", models.CharField(blank=True, max_length=100)),
                (
                    "checkin_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="checkin_photos/%Y/%m/"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "marked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marked_attendances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "class_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendances",
                        to="attendance.classsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-check_in_time"],
                "unique_together": {("user", "date")},
            },
        ),
    ]
