# Generated by Django 5.0.4 on 2026-04-25 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "attendance",
            "0002_alter_attendance_unique_together_attendance_subject_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classsession",
            name="classroom_photo",
        ),
    ]
